/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface AddRaceResultRequestDTO {
  /** @nullable */
  trackId?: string | null;
  /** @nullable */
  trackName?: string | null;
  time?: number;
}
