/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface AdminUnlockModelRequestDTO {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  modelId?: string | null;
}
