/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface AdminUserResponseDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  email?: string | null;
  isActive?: boolean;
  isGuest?: boolean;
  isAdmin?: boolean;
  createdAt?: string;
  /** @nullable */
  lastLoginAt?: string | null;
  lastSeen?: string;
}
