/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface AdminCustomCheckoutRequestDTO {
  unitAmount?: number;
  /** @nullable */
  customerEmail?: string | null;
  /** @nullable */
  productDescription?: string | null;
}
