/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { UserDTO } from './userDTO';

export interface CampaignRecipientDTO {
  /** @nullable */
  id?: string | null;
  /** @minLength 1 */
  campaignId: string;
  /** @minLength 1 */
  userId: string;
  user?: UserDTO;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  status: string;
  /** @nullable */
  sentAt?: string | null;
  /** @nullable */
  openedAt?: string | null;
  /** @nullable */
  errorMessage?: string | null;
  /** @nullable */
  lastSeenBefore?: string | null;
  createdAt?: string;
}
