/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface ClaudeMessageRequestDTODTO {
  /** @nullable */
  message?: string | null;
  /** @nullable */
  model?: string | null;
  maxTokens?: number;
  temperature?: number;
  /** @nullable */
  conversationId?: string | null;
}
