/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface ClaudeStreamResponseDTODTO {
  /** @nullable */
  eventType?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  toolName?: string | null;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  toolInput?: string | null;
  /** @nullable */
  toolResult?: string | null;
}
