/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export type ClaudeToolTypeDTO = typeof ClaudeToolTypeDTO[keyof typeof ClaudeToolTypeDTO];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaudeToolTypeDTO = {
  None: 'None',
  Weather: 'Weather',
  Search: 'Search',
  Calculator: 'Calculator',
} as const;
