/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface CreateGuestRequestDTO {
  /** @nullable */
  guestId?: string | null;
  /** @nullable */
  guestKey?: string | null;
}
