/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface CreateCampaignRequestDTO {
  /** @nullable */
  name: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  emailTemplateId: string | null;
  /** @nullable */
  userIds: string[] | null;
}
