/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface DashboardStatsDtoDTO {
  newUsersInPeriod?: number;
  returningUsersInPeriod?: number;
  retentionRate?: number;
  churnRate?: number;
  dailyActiveUsers?: number;
  weeklyActiveUsers?: number;
  monthlyActiveUsers?: number;
  totalUsersLoggedIn?: number;
  uniqueUsersLoggedIn?: number;
  averageSessionDuration?: number;
  totalQuestsCompleted?: number;
  totalRacesCompleted?: number;
  totalKilometersDriven?: number;
  averageSpeed?: number;
  concurrentPlayers?: number;
  totalAIMessagesSent?: number;
  uniqueUsersUsingAI?: number;
  averageAIMessagesPerUser?: number;
  startDate?: string;
  endDate?: string;
}
