/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface EnhanceMessageResponseDTODTO {
  /** @nullable */
  alternatives?: string[] | null;
}
