/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { SimCardDTO } from './simCardDTO';

export interface FindSimsResponseDTODTO {
  /** @nullable */
  items?: SimCardDTO[] | null;
}
