/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { GameStatisticsDTOPeakHours } from './gameStatisticsDTOPeakHours';
import type { TopPlayerPreviewDTO } from './topPlayerPreviewDTO';

export interface GameStatisticsDTO {
  totalPlayers?: number;
  onlinePlayers?: number;
  activePlayers24h?: number;
  averagePlayTime?: string;
  totalGameTime?: string;
  /** @nullable */
  peakHours?: GameStatisticsDTOPeakHours;
  longestSession?: string;
  averageSessionLength?: string;
  /** @nullable */
  topPlayers?: TopPlayerPreviewDTO[] | null;
}
