/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export type GetApiUsersParams = {
Page?: number;
PageSize?: number;
SearchTerm?: string;
SortBy?: string;
SortDescending?: boolean;
IsActive?: boolean;
HasPaid?: boolean;
LastLoginFrom?: string;
LastLoginTo?: string;
CreatedFrom?: string;
CreatedTo?: string;
};
