/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export type GetApiOpenrouterToolsChatStreamParams = {
conversationId?: string;
message?: string;
};
