/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface GrantPremiumModelsResponseDTO {
  usersProcessed?: number;
  modelsGranted?: number;
  /** @nullable */
  message?: string | null;
}
