/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { ModelObjectDTO } from './modelObjectDTO';

export interface IModelConfigDTO {
  model?: ModelObjectDTO;
}
