/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { FileUploadDtoDTO } from './fileUploadDtoDTO';

export interface InitiateUploadResponseDTO {
  /** @nullable */
  uploadUrl?: string | null;
  fileInfo?: FileUploadDtoDTO;
}
