/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface LastPositionDTO {
  /** @nullable */
  x?: number | null;
  /** @nullable */
  y?: number | null;
  /** @nullable */
  z?: number | null;
  /** @nullable */
  rotationX?: number | null;
  /** @nullable */
  rotationY?: number | null;
  /** @nullable */
  rotationZ?: number | null;
}
