/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface LocationInfoDTO {
  /** @nullable */
  lat?: number | null;
  /** @nullable */
  lng?: number | null;
  /** @nullable */
  cell_id?: number | null;
  /** @nullable */
  location_area_code?: number | null;
  /** @nullable */
  accuracy?: number | null;
}
