/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface ModelFileUploadResponseDTO {
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  fileType?: string | null;
  /** @nullable */
  fileUrl?: string | null;
  updatedAt?: string;
}
