/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { ModelRotationDTO } from './modelRotationDTO';

export interface ModelObjectDTO {
  /** @nullable */
  obj?: string | null;
  /** @nullable */
  type?: string | null;
  scale?: number;
  /** @nullable */
  units?: string | null;
  rotation?: ModelRotationDTO;
  /** @nullable */
  anchor?: string | null;
  /** @nullable */
  elevationOffset?: number | null;
  /** @nullable */
  screenshot?: string | null;
}
