/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { IModelConfigDTO } from './iModelConfigDTO';

export interface ModelDetailsDtoDTO {
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  configJson?: string | null;
  config?: IModelConfigDTO;
  price?: number;
  isPremium?: boolean;
  isActive?: boolean;
  /** @nullable */
  thumbnailUrl?: string | null;
  /** @nullable */
  thumbnailFileId?: string | null;
  /** @nullable */
  modelUrl?: string | null;
  /** @nullable */
  modelFileId?: string | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  screenshot?: string | null;
  isUnlocked?: boolean;
  isFeatured?: boolean;
  /** @nullable */
  createdById?: string | null;
}
