/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface ModelInfoDtoDTO {
  /** @nullable */
  modelId?: string | null;
  /** @nullable */
  name?: string | null;
  price?: number;
  isPremium?: boolean;
  isUnlocked?: boolean;
}
