/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface NetworkInfoDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  country_code?: string | null;
  /** @nullable */
  mcc?: string | null;
  /** @nullable */
  mnc?: string | null;
}
