/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface RaceRecordResponseDTO {
  /** @nullable */
  personalBest?: number | null;
  /** @nullable */
  trackRecord?: number | null;
  /** @nullable */
  trackRecordHolder?: string | null;
}
