/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface RaceResultResponseDTO {
  isPersonalBest?: boolean;
  isTrackRecord?: boolean;
  /** @nullable */
  previousPersonalBest?: number | null;
  /** @nullable */
  previousTrackRecord?: number | null;
}
