/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface RequestOtpResponseDTO {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  isExistingUser?: boolean;
  /** @nullable */
  expiresAt?: string | null;
}
