/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface RequestOtpRequestDTO {
  /** @minLength 1 */
  email: string;
  /** @nullable */
  guestId?: string | null;
  /** @nullable */
  guestKey?: string | null;
}
