/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SendSmsResponseDTODTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  from?: string | null;
  /** @nullable */
  to?: string | null;
  /** @nullable */
  message?: string | null;
  parts?: number;
}
