/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SendSMSRequestDTO {
  /**
   * @minLength 1
   * @pattern ^[a-zA-Z0-9]{1,11}|\+[1-9]\d{1,14}$
   */
  from: string;
  /**
   * @minLength 0
   * @maxLength 1600
   */
  message: string;
  /**
   * @minLength 1
   * @pattern ^\+[1-9]\d{1,14}$
   */
  to: string;
}
