/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SendSMSResponseDTO {
  cost?: number;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  direction?: string | null;
  /** @nullable */
  from?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  message?: string | null;
  parts?: number;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  to?: string | null;
}
