/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SetUserPaidRequestDTO {
  /** @nullable */
  stripeCustomerId?: string | null;
  confirm?: boolean;
}
