/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { NetworkInfoDTO } from './networkInfoDTO';
import type { TagInfoDTO } from './tagInfoDTO';
import type { LocationInfoDTO } from './locationInfoDTO';

export interface SimCardDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  iccid?: string | null;
  /** @nullable */
  label?: string | null;
  /** @nullable */
  network_whitelist?: string | null;
  /** @nullable */
  imei_lock?: string | null;
  /** @nullable */
  connector?: string | null;
  activated?: boolean;
  /** @nullable */
  online_at?: string | null;
  /** @nullable */
  last_came_online_at?: string | null;
  network?: NetworkInfoDTO;
  /** @nullable */
  ipv4?: string | null;
  usage?: number;
  /** @nullable */
  tags?: TagInfoDTO[] | null;
  location?: LocationInfoDTO;
}
