/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SmsMessageResponseDTODTO {
  id?: string;
  /** @nullable */
  from?: string | null;
  /** @nullable */
  to?: string | null;
  /** @nullable */
  message?: string | null;
  sentAt?: string;
  /** @nullable */
  status?: string | null;
}
