/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export type StreamEventTypeDTO = typeof StreamEventTypeDTO[keyof typeof StreamEventTypeDTO];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamEventTypeDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
