/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export type StreamStateDTO = typeof StreamStateDTO[keyof typeof StreamStateDTO];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamStateDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
