/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface TagInfoDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  id?: string | null;
  can_write?: boolean;
  /** @nullable */
  color?: string | null;
}
