/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface ToplistEntryDTO {
  /** @nullable */
  playerId?: string | null;
  /** @nullable */
  playerName?: string | null;
  rank?: number;
  value?: string;
  /** @nullable */
  valueString?: string | null;
}
