/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface UnlockedModelDtoDTO {
  /** @nullable */
  modelId?: string | null;
  purchasedAt?: string;
}
