/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface UpdateModelRequestDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  configJson?: string | null;
  /** @nullable */
  isPremium?: boolean | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  thumbnailFileId?: string | null;
  /** @nullable */
  modelFileId?: string | null;
}
