/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface UserDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  normalizedUserName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  normalizedEmail?: string | null;
  emailConfirmed?: boolean;
  /** @nullable */
  passwordHash?: string | null;
  /** @nullable */
  securityStamp?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  twoFactorEnabled?: boolean;
  /** @nullable */
  lockoutEnd?: string | null;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  isActive?: boolean;
  isGuest?: boolean;
  isAdmin?: boolean;
  /** @nullable */
  guestKey?: string | null;
  readonly createdAt?: string;
  /** @nullable */
  readonly lastLoginAt?: string | null;
  readonly lastSeen?: string;
  hasPaid?: boolean;
  /** @nullable */
  stripeCustomerId?: string | null;
  /** @nullable */
  paidAt?: string | null;
  /** @nullable */
  readonly otpCode?: string | null;
  /** @nullable */
  readonly otpExpiration?: string | null;
  isEmailVerified?: boolean;
  isLowPerformanceDevice?: boolean;
  readonly isSubscribedToEmails?: boolean;
}
