/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface VerifyOtpRequestDTO {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  otpCode: string;
  isLowPerformanceDevice?: boolean;
}
